// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJy-u2-Wqi8ICJVJubrqNQtfjj9CBoi3A',
    appId: '1:597002820147:web:fabb80a5eb66df63dd6146',
    messagingSenderId: '597002820147',
    projectId: 'kudosware-e898c',
    authDomain: 'kudosware-e898c.firebaseapp.com',
    storageBucket: 'kudosware-e898c.appspot.com',
    measurementId: 'G-K2BWTCJ7SM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwJLJAC1U6pR8hHzwwNlvC_ZnxhgtRFo0',
    appId: '1:597002820147:android:cca61908ac9c09fedd6146',
    messagingSenderId: '597002820147',
    projectId: 'kudosware-e898c',
    storageBucket: 'kudosware-e898c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI2Of6jkLG3YSLft195hienMSyK-heNRk',
    appId: '1:597002820147:ios:a69dc0c4dcee1103dd6146',
    messagingSenderId: '597002820147',
    projectId: 'kudosware-e898c',
    storageBucket: 'kudosware-e898c.appspot.com',
    iosBundleId: 'com.example.studentManage',
  );
}
